version: "3.8"
services:
  bashls:
    image: lspcontainers/bash-language-server
    build:
      context: servers/bashls

  clangd:
    image: lspcontainers/clangd-language-server
    build:
      context: servers/clangd

  dockerls:
    image: lspcontainers/docker-language-server
    build:
      context: servers/dockerls

  graphql-lsp:
    image: lspcontainers/graphql-language-service-cli
    build:
      context: servers/graphql-lsp

  gopls:
    image: lspcontainers/gopls
    build:
      context: servers/gopls

  html:
    image: lspcontainers/html-language-server
    build:
      context: servers/html

  intelephense:
    image: lspcontainers/intelephense
    build:
      context: servers/intelephense

  jsonls:
    image: lspcontainers/json-language-server
    build:
      context: servers/jsonls

  omnisharp:
    image: lspcontainers/csharp-language-server
    build:
      context: servers/omnisharp

  powershell_es:
    image: lspcontainers/powershell-language-server
    build:
      context: servers/powershell_es

  prisma:
    image: lspcontainers/prisma-language-server
    build:
      context: servers/prisma

  pylsp:
    image: lspcontainers/python-lsp-server
    build:
      context: servers/pylsp

  pyright:
    image: lspcontainers/pyright-langserver
    build:
      context: servers/pyright

  rust_analyzer:
    image: lspcontainers/rust-analyzer
    build:
      context: servers/rust_analyzer

  sumneko_lua:
    image: lspcontainers/lua-language-server
    build:
      context: servers/sumneko_lua

  svelteserver:
    image: lspcontainers/svelte-language-server
    build:
      context: servers/svelteserver

  tailwindcss:
    image: lspcontainers/tailwindcss-language-server
    build:
      context: servers/tailwindcss

  terraformls:
    image: lspcontainers/terraform-ls
    build:
      context: servers/terraformls

  tsserver:
    image: lspcontainers/typescript-language-server
    build:
      context: servers/tsserver

  yamlls:
    image: lspcontainers/yaml-language-server
    build:
      context: servers/yamlls

  vuels:
    image: lspcontainers/vue-language-server
    build:
      context: servers/vuels
